FROM python:3

RUN mkdir -p /etc/uwsgi/
WORKDIR /etc/uwsgi/
ADD deploy/docktor.ini /etc/uwsgi/

WORKDIR /etc/systemd/system/
ADD deploy/uwsgi.service /etc/systemd/system/

RUN mkdir /data
WORKDIR /data
ADD requirements.txt /data
RUN pip install --no-cache-dir -r requirements.txt
ADD . /data
